require:
  - rubocop-rspec
  - rubocop-rails         

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 30  

Metrics/BlockLength:
  Max: 100  

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 50

AllCops:
  Exclude:
    - 'bin/bundle'